[package]
name = "pastry-management-desktop"
version = "0.1.0"
description = "Pastry Management desktop application"
authors = ["Pastry Management contributors"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "pastry_management_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.32", features = ["bundled"] }
thiserror = "1"
argon2 = "0.5"
rand_core = { version = "0.6", features = ["getrandom"] }
uuid = { version = "1", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
zip = { version = "8.6.0", default-features = false, features = ["deflate"] }
sha2 = "0.11.0"
tauri-plugin-dialog = "2.7.3"
reqwest = { version = "0.13.5", features = ["form", "json"] }
async-trait = "0.1.92"
keyring = { version = "4.2.0", features = ["apple-native-keyring-store"] }
base64 = "0.23.1"
rand = "0.10.3"
tokio = { version = "1.53.1", features = ["fs", "time", "rt", "macros"] }
tauri-plugin-updater = "2"


# Read the optimization guideline for more details: https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true

[dev-dependencies]
mockito = "1.7.2"
